### ISSUE TITLE
Cli fails to deserialize a custom pattern created with PatternEditor

### ISSUE THREAD

**Issue by mogulano** [PositiveTechnologies/PT.PM#136]

**Comment by KvanTTT** [comment]
Could you please provide the full cli params string with pattern?

**Comment by mogulano** [comment]
So I have created this `custom_patterns.json` with a help of the editor:
```
[
  {
    "Name": "MD5",
    "Key": "f2188439-9ef0-49be-8a70-1f284f5938b1",
    "Languages": [
      "CSharp",
      "Uncertain"
    ],
    "DataFormat": "",
    "Value": "MD5.Create(...);",
    "CweId": "",
    "Description": "",
    "FilenameWildcard": ""
  }
]
```
and I get `Unexpected character encountered while parsing value: M. Path '', line 0, position 0.`

Params are very simple: `-f C:\sources\file.cs --patterns C:\Users\name\AppData\Local\PT.PM\custom_patterns.json`

**Comment by KvanTTT** [comment]
You forgot to fill `DataFormat`. Valid json is:

```json
[
    {
      "Name": "MD5",
      "Key": "f2188439-9ef0-49be-8a70-1f284f5938b1",
      "Languages": [
        "CSharp",
        "Uncertain"
      ],
      "DataFormat": "DSL",
      "Value": "MD5.Create(...);",
      "CweId": "",
      "Description": "",
      "FilenameWildcard": ""
    }
  ]
```

**Comment by KvanTTT** [comment]
@mogulano is your problem resolved? Can we close this issue?

**Comment by mogulano** [comment]
Thanks, it solves the exception.
However I've created the json in the Pattern Editor. Is it something I didn't mark in the editor? Could you please point me to the UI element? I tried to find it myself unsuccessfully.

**Comment by KvanTTT** [comment]
You can copy pattern json description from Json textbox and it works fine. What version of PT.PM do you use?

![image](https://user-images.githubusercontent.com/1150330/41226850-6bef94a6-6d7b-11e8-9602-d44199fafe50.png)

**Comment by mogulano** [comment]
Hi, Sorry for the delay. I used the latest commit https://github.com/PositiveTechnologies/PT.PM/commit/7c152e19dc61685842c43db43164a0aed65125f0 from Master branch.
My screen looks like that. Please notice that `MD5.Create` is for C#, not PHP:
![image](https://user-images.githubusercontent.com/38420246/41466994-54b3360a-70ad-11e8-9768-a5df789934bb.png)

I pressed Create, typed a name, unmarked all checkboxes exept C#, typed search value. My Json text box is:
```
{
  "Kind": "PatternRoot",
  "Languages": [
    "CSharp",
    "Uncertain"
  ],
  "Node": {
    "Kind": "PatternInvocationExpression",
    "Target": {
      "Kind": "PatternMemberReferenceExpression",
      "Target": {
        "Kind": "PatternIdToken",
        "Id": "MD5"
      },
      "Name": {
        "Kind": "PatternIdToken",
        "Id": "Create"
      }
    },
    "Arguments": {
      "Kind": "PatternArgs",
      "Args": [
        {
          "Kind": "PatternMultipleExpressions"
        }
      ]
    }
  },
  "CodeFile": {
    "Code": "MD5.Create(...);"
  }
}
```
My custom_patterns.json is
```
[
  {
    "Name": "MD5",
    "Key": "f2188439-9ef0-49be-8a70-1f284f5938b1",
    "Languages": [
      "CSharp",
      "Uncertain"
    ],
    "DataFormat": "",
    "Value": "MD5.Create(...);",
    "CweId": "",
    "Description": "",
    "FilenameWildcard": ""
  },
  {
    "Name": "MD5v2",
    "Key": "cc5d2cd4-6bdf-40d4-a889-4da36f504a4f",
    "Languages": [
      "CSharp",
      "Uncertain"
    ],
    "DataFormat": "",
    "Value": "MD5.Create(...);",
    "CweId": "",
    "Description": "",
    "FilenameWildcard": ""
  }
]
```

**Comment by mogulano** [comment]
I have tried without altering any checkbox and got the same empty DataFormat. I think we are using different branches.

**Comment by KvanTTT** [comment]
Could you please try the version from the latest `dev` branch?

**Comment by mogulano** [comment]
The same :(
