### ISSUE TITLE
Match fully qualified name

### ISSUE THREAD

**Issue by mogulano** [PositiveTechnologies/PT.PM#156]
I'm trying to match object creation by fully qualified name, like:
```java
public class ProcessBuilderExample
{
    public static void main(String[] args)
    {
        ProcessBuilder pb = new Java.Lang.ProcessBuilder("bbb", "aaa");
        Process process = pb.start();
    }
}
```
But patterns `new <[(Java\s*\.\s*Lang\s*\.\s*)?ProcessBuilder]>(...);` or `new (Java\s*\.\s*Lang\s*\.\s*)?ProcessBuilder(...);` don't match.

`new ProcessBuilder(...);` works perfectly for `new ProcessBuilder("bbb", "aaa");`

How to do it in DSL?

**Comment by mogulano** [comment]
Thanks! It wasn't clear if it a missing feature or I just don't know DSL well enough.
Question though: I guess I can have two patterns for both cases, but is it possible to write a single pattern to match `new Java.Lang.ProcessBuilder("bbb", "aaa");` and `new ProcessBuilder("bbb", "aaa");`?

**Comment by KvanTTT** [comment]
Yes, you can:

```
new ProcessBuilder(...) <|> new Java.Lang.ProcessBuilder(...)
```

Grammar is also available here: https://github.com/PositiveTechnologies/PT.PM/blob/dev/Sources/PT.PM.Dsl/DslParser.g4

We are going to rewrite DSL in the future. This is the first version, not very successful.

But it's always possible to use JSON. See samples from [PatternTests](https://github.com/PositiveTechnologies/PT.PM/blob/dev/Sources/PT.PM.Tests/PatternTests.cs).
