### ISSUE TITLE
Add raw ust nodes (RawTextUst, RawToken, RawTokenUst, RawUst)

### ISSUE THREAD

**Issue by KvanTTT** [PositiveTechnologies/PT.PM#165]
### RawTextUst

Will be used for code span that we don't care about at least for the current time. It contains only `TextSpan` without text itself. It allows supporting new languages very easy with regex: just declare `RawTextUst` for entire file and match it with `PatternAny`.

### RawTokenUst

The same as `RawTextUst` but contains the list of tokens (or span of tokens). It allows supporting new languages or language construction with implemented lexer but without a parser.

### RawUst

Maybe it's better to use the `RawUst` instead of `RawTokenUst`. It will contain the list of `Ust`.

### RawToken

Token with unknow type.

**Comment by gabriel-fallen** [comment]
Reminds me of ["Microparsers"] approach.

The basic idea is to skip most of the syntax and only parse the tokens relevant for analysis. Then we can check certain properties and detect some issues. As long as many languages have very similar syntax (for instance, C, C++, Java, C#, JavaScript, Dart) many parsers and checks work for all of them without modifications.

Sure enough this approach has it's limitations...

["Microparsers"]: https://blog.acolyer.org/2016/05/31/how-to-build-static-checking-systems-using-orders-of-magnitude-less-code/
