### ISSUE TITLE
Support for PatternUnaryOperatorExpression and PatternUnaryOperatorLiteral

### ISSUE THREAD

**Issue by flippaa** [PositiveTechnologies/PT.PM#179]
Add support for that nodes similar to already existing **PatternBinaryOperatorExpression** and **PatternBinaryOperatorLiteral**.

**Comment by KvanTTT** [comment]
fixed by https://github.com/PositiveTechnologies/PT.PM/commit/a12bd4a5cfa8a50bbc6207f8bb63d88e40b5ea1e
