### ISSUE TITLE
Write doc about samples and API

### ISSUE THREAD

**Issue by KvanTTT** [PositiveTechnologies/PT.PM#21]
Translate it after.

**Comment by ruadmjn** [comment]
What about some little description?
I can translate my comments in repo:[basicPM](https://github.com/ruadmjn/basicPM) to help with it

**Comment by KvanTTT** [comment]
Good sample! But I'll rewrite it with respect to the new `Workflow` structure and `WorkflowResult` class. See also #17. Serialization and other internals will be hidden inside `Workflow.Process` method. I'll do it on the following week.

**Comment by KvanTTT** [comment]
Done in [Wiki](https://github.com/PositiveTechnologies/PT.PM/wiki) both for Russian and English.
