### ISSUE TITLE
Implement UAST dump mode for PT.PM.Cli

### ISSUE THREAD

**Issue by kochetkov** [PositiveTechnologies/PT.PM#59]
Implement an additional PT.PM.Cli's operation mode `--dump-uast` which allows to serialize and dump UAST without any matching against patterns. Dump should be saved to the named pipe or stdout (console) and contain a set of pairs `Full file name` -> `UAST` serialized to JSON for all processed sources.

**Comment by KvanTTT** [comment]
As I understand it should work with the only single file, not a directory?

**Comment by kochetkov** [comment]
If the implementation of batch processing of all files from a given directory is easy, then it is worth implementing it. If there are any difficulties with this, then it is worthwhile to implement the processing of one file at a time.

**Comment by KvanTTT** [comment]
Done in my [dump-ust](https://github.com/KvanTTT/PT.PM/tree/dump-ust) branch. I also added parameters description to Wiki: [--dump-ust](https://github.com/PositiveTechnologies/PT.PM/wiki/CLI#--dump-ust).

Please take a look.
