### ISSUE TITLE
about  cfg  and  pdg

### ISSUE THREAD

**Issue by tiandiyixian** [PositiveTechnologies/PT.PM#69]
hi，
    I found  cfg  and pdg modul  in  this  projecte,but they are not  implemented。how can I implement  such  as simple   defect  analysis：
    $ a=_GET["taint"];
    $b=$a;
 echo $b;
  or       taint  flow  about     interprocedural dependence analysis？any  suggestion  will   be  usefull！thanks  a  lot.

**Comment by KvanTTT** [comment]
Hi! Such functionality included in our private commercial project. This won't be opened, sorry.
